### ISSUE TITLE
ArgumentNullException in TeeChart.Maui.Gallery

### ISSUE THREAD

**Issue by taimo42** [Steema/TeeChart-NET-Pro-Samples#1]
Hi, 
I'm having trouble when trying out the Maui example for the TeeChart control.
Here are the details:

### Development Environment
- Microsoft Windows 10 Pro, Version 21H2, OS build 19044.2130
- Microsoft Visual Studio Professional 2022 (64-bit)  - Version 17.3.6

### Steps to reproduce
- Download this repository
- Open 'TeeChart-NET-Pro-Samples-main\MAUI\TeeChart.Maui.Gallery\TeeChart.Maui.Gallery.sln' in Visual Studio
- Select 'Windows Machine' as the target
- Build and Run the solution

### Result
System.ArgumentNullException
  HResult=0x80004003
  Message=Value cannot be null. (Parameter 'type')
  Source=System.Private.CoreLib
  StackTrace:
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at Steema.TeeChart.Drawing.Shape.get_Pen()
   at Steema.TeeChart.Panel..ctor(Chart c)
   at Steema.TeeChart.Chart.InitVars()
   at TeeChart.Maui.ChartView..ctor()
   at TeeChart.Maui.Gallery.MainPage.OnCounterClicked(Object sender, EventArgs e) in .....\TeeChart-NET-Pro-Samples-main\MAUI\TeeChart.Maui.Gallery\MainPage.xaml.cs:line 25
   at TeeChart.Maui.Gallery.MainPage..ctor() in .....\TeeChart-NET-Pro-Samples-main\MAUI\TeeChart.Maui.Gallery\MainPage.xaml.cs:line 11
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)

Can someone help me make this working?

**Comment by PepJorge** [comment]
> Hi, I'm having trouble when trying out the Maui example for the TeeChart control. Here are the details:
> 
> ### Development Environment
> * Microsoft Windows 10 Pro, Version 21H2, OS build 19044.2130
> * Microsoft Visual Studio Professional 2022 (64-bit)  - Version 17.3.6
> 
> ### Steps to reproduce
> * Download this repository
> * Open 'TeeChart-NET-Pro-Samples-main\MAUI\TeeChart.Maui.Gallery\TeeChart.Maui.Gallery.sln' in Visual Studio
> * Select 'Windows Machine' as the target
> * Build and Run the solution
> 
> ### Result
> System.ArgumentNullException HResult=0x80004003 Message=Value cannot be null. (Parameter 'type') Source=System.Private.CoreLib StackTrace: at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes) at Steema.TeeChart.Drawing.Shape.get_Pen() at Steema.TeeChart.Panel..ctor(Chart c) at Steema.TeeChart.Chart.InitVars() at TeeChart.Maui.ChartView..ctor() at TeeChart.Maui.Gallery.MainPage.OnCounterClicked(Object sender, EventArgs e) in .....\TeeChart-NET-Pro-Samples-main\MAUI\TeeChart.Maui.Gallery\MainPage.xaml.cs:line 25 at TeeChart.Maui.Gallery.MainPage..ctor() in .....\TeeChart-NET-Pro-Samples-main\MAUI\TeeChart.Maui.Gallery\MainPage.xaml.cs:line 11 at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
> 
> Can someone help me make this working?

Yes, the TeeChart for MAUI Windows platform part still giving some problems. For the moment only the other platforms (Android, iOS and MacOS) are available.
We hope to have working on Windows plarform shortly.
Thanks.
